# Numpy

`NumPy` es una librería para hacer computos numéricos en Python. Es la base de muchas otras librerías científicas. Entre otras cosas, nos permite:

- Utilizar arreglos multidimensionales.
- Utilizar funciones matemáticas.
- Utilizar herramientas de álgebra lineal.

Necesitamos conocer esta librería (en concreto, el manejo de arreglos) para poder entender el funcionamiento de `pandas`. 

### Requisitos

Para esta clase necesitamos tener instalada la librería numpy:

```
pip3 install --upgrade numpy
```

Para comenzar a trabajar vamos a importar la librería y crear un pequeño arreglo de elementos aleatorios.

In [1]:
import numpy as np

data = np.random.randn(2,4)
data

array([[ 0.15319926,  0.33625343, -0.12596414, -0.7659216 ],
       [-0.58980604, -0.47173065,  1.35623028,  0.0915713 ]])

A diferencia de una lista, podemos hacer operaciones matriciales, como multiplicar el arreglo `data` por un escalar:

In [2]:
data*10

array([[ 1.53199256,  3.3625343 , -1.25964137, -7.65921602],
       [-5.89806042, -4.71730653, 13.56230278,  0.91571304]])

o sumarle una matriz:

In [3]:
data + data

array([[ 0.30639851,  0.67250686, -0.25192827, -1.5318432 ],
       [-1.17961208, -0.94346131,  2.71246056,  0.18314261]])

### Crear arreglos

Podemos crear arreglos a partir de una lista:

In [4]:
data1 = [1, 1, 2, 3, 5]
arr1 = np.array(data1)
arr1

array([1, 1, 2, 3, 5])

In [11]:
data2 = [[1, 1, 2, 3], [5, 8, 13, 21]]
arr2 =np.array(data2)
arr2

array([[ 1,  1,  2,  3],
       [ 5,  8, 13, 21]])

Para preguntar el número de dimensiones utilizamos `ndim`. Para preguntar las dimensiones utilizamos `shape`.

In [12]:
arr2.ndim

2

In [13]:
arr2.shape

(2, 4)

### Accediendo a elementos

Para obtener un elemento:

In [14]:
arr1[2]

2

In [15]:
arr2[1][2]

13

In [16]:
# Podemos acceder de esta forma también.
arr2[1, 2]

13

Los arreglos son mutables:

In [17]:
arr1[3] = 300
arr1

array([  1,   1,   2, 300,   5])

In [18]:
arr2[1, 2] = 100
arr2

array([[  1,   1,   2,   3],
       [  5,   8, 100,  21]])

### arange

También tenemos un equivalente a `range` llamado `arange`, pero que genera un arreglo.

In [19]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Operaciones sobre arreglos

Algunas operaciones que se pueden hacer sobre un arreglo son:

In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr * arr

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [22]:
arr + 1

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [23]:
(arr + 1) - arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
1 / arr

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [25]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

### _Slices_

Podemos extraer partes de un arreglo tal como en las listas. También podemos usar esto para cambiar los valores de dichos elementos.

In [26]:
arr = np.arange(3,15)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr[3:6]

array([6, 7, 8])

In [29]:
arr[3:6] = 1
arr

array([ 3,  4,  5,  1,  1,  1,  9, 10, 11, 12, 13, 14])

### Indexando con booleanos

Podemos utilizar comparaciones booleanas con los arreglos:

In [30]:
arr = np.array([0, 0, 1, 1, 2, 2])
arr == 1

array([False, False,  True,  True, False, False])

Y usarlo para acceder a valores en otros arreglos. Vamos a crear un arreglo multidimensional e ingresar el arreglo anterior como índice:

In [31]:
arr2 = np.random.randn(6, 3)
arr2

array([[ 0.39754381, -1.29167182, -0.5411754 ],
       [-0.02392931, -1.11918671,  0.2881838 ],
       [-0.64945636,  0.11199294,  0.65555976],
       [ 0.9832492 , -0.85611816,  0.71909869],
       [-1.99903501, -1.9495602 ,  0.90343025],
       [-0.04137128,  1.2252531 , -0.34718251]])

In [32]:
arr2[arr == 1]

array([[-0.64945636,  0.11199294,  0.65555976],
       [ 0.9832492 , -0.85611816,  0.71909869]])

Y también podemos negar la condición:

In [33]:
arr2[~(arr == 1)]

array([[ 0.39754381, -1.29167182, -0.5411754 ],
       [-0.02392931, -1.11918671,  0.2881838 ],
       [-1.99903501, -1.9495602 ,  0.90343025],
       [-0.04137128,  1.2252531 , -0.34718251]])

### Transponer un arreglo

Es posible obtener la transpuesta de un arreglo rápidamente.

In [37]:
arr = np.random.randn(6, 3)
arr

array([[ 0.15920914,  0.05229821, -0.19296301],
       [-0.37946029,  0.122006  , -0.19017146],
       [-0.78677894, -0.35637733, -0.18941291],
       [-0.00765847,  2.04357794, -0.32941621],
       [ 0.89687296,  1.14051443, -0.69261992],
       [ 1.3606585 , -0.55382145,  0.15436516]])

In [38]:
arr.T

array([[ 0.15920914, -0.37946029, -0.78677894, -0.00765847,  0.89687296,
         1.3606585 ],
       [ 0.05229821,  0.122006  , -0.35637733,  2.04357794,  1.14051443,
        -0.55382145],
       [-0.19296301, -0.19017146, -0.18941291, -0.32941621, -0.69261992,
         0.15436516]])

### Otras funciones

Tenemos acceso a algunas funciones de estadística básicas. Por ejemplo `sum`, `mean` y `std` nos permiten respectivamente sacar la suma, el promedio y la desviación estándar de un arreglo.

In [39]:
arr = np.random.randn(10)
arr

array([ 0.89785463, -1.51262834, -1.63271519,  0.34629049, -0.52690398,
       -0.54982572,  0.5535778 ,  1.15683601,  0.12698068,  0.03332928])

In [40]:
arr.sum()

-1.107204342790007

In [41]:
arr.mean()

-0.11072043427900069

In [42]:
arr.std()

0.8943803603711583

También podemos ordenar:

In [43]:
arr.sort()
arr

array([-1.63271519, -1.51262834, -0.54982572, -0.52690398,  0.03332928,
        0.12698068,  0.34629049,  0.5535778 ,  0.89785463,  1.15683601])

Y pedir elementos distintos:

In [44]:
arr = np.array([0, 0, 1, 1, 2, 2])
np.unique(arr)

array([0, 1, 2])